import type { NextPage } from "next";
import Head from "next/head";
import { Axios } from "./api/axios";

const Home: NextPage = () => {
  const res = Axios.get("/item").then((res) => {
    console.log(res.data);
  });

  return (
    <div>
      <Head>
        <title>Hisoka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Hellow Next</p>
    </div>
  );
};

export default Home;
